/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewServidor;

import Model.ServidorUDP;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gabriel
 */
public class GUIServidor extends JFrame {
    private DefaultTableModel modeloTabelaSalas;
    private DefaultTableModel modeloTabelaUsuarios;
    private ServidorUDP servidor;

    /**
     * Creates new form GUIServidor
     */
    public GUIServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPorta = new javax.swing.JLabel();
        textfieldPorta = new javax.swing.JTextField();
        buttonConfirmar = new javax.swing.JButton();
        paneSalas = new javax.swing.JScrollPane();
        tabelaSalas = new javax.swing.JTable();
        paneUsuarios = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPorta.setText("Porta:");

        textfieldPorta.setText("Digite a porta para iniciar o servidor");

        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        tabelaSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        paneSalas.setViewportView(tabelaSalas);

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        paneUsuarios.setViewportView(tabelaUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPorta)
                        .addGap(18, 18, 18)
                        .addComponent(textfieldPorta, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(buttonConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paneSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addComponent(paneUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPorta)
                    .addComponent(textfieldPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonConfirmar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(paneSalas, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        servidor = new ServidorUDP();
        servidor.setPorta(Integer.parseInt(textfieldPorta.getText()));
        servidor.init();
        modeloTabelaSalas = servidor.getModeloTabelaSalas();
        modeloTabelaUsuarios = servidor.getModeloTabelaUsuarios();
        tabelaSalas.setModel(modeloTabelaSalas);
        tabelaUsuarios.setModel(modeloTabelaUsuarios);
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    public void disableButtonConfirmar() {
        buttonConfirmar.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton buttonConfirmar;
    private javax.swing.JLabel labelPorta;
    private javax.swing.JScrollPane paneSalas;
    private javax.swing.JScrollPane paneUsuarios;
    private javax.swing.JTable tabelaSalas;
    private javax.swing.JTable tabelaUsuarios;
    private javax.swing.JTextField textfieldPorta;
    // End of variables declaration//GEN-END:variables
}