/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModelCliente;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author tofet
 */
public class ViewDiscussao extends javax.swing.JFrame {

    private DefaultTableModel modeloTabelaUsuarios;
    private DefaultTableModel modeloTabelaVotos;
    private ModelCliente cliente;
    private StyledDocument doc;
    private Style style;
    private DateFormat df;
    
    public ViewDiscussao() {
        initComponents();
        doc = new DefaultStyledDocument();
        StyleContext context = new StyleContext();
        style = context.addStyle("test", null);
        StyleConstants.setForeground(style, Color.BLACK);
        jMessagePane.setEditable(false);
        df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    }
    
    public void setCliente(ModelCliente client){
        cliente = client;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneUsers = new javax.swing.JScrollPane();
        tabelaUsers = new javax.swing.JTable();
        paneConversa = new javax.swing.JScrollPane();
        jMessagePane = new javax.swing.JTextPane();
        jSairSala = new javax.swing.JButton();
        jMensagem = new javax.swing.JTextField();
        buttonEnviar = new javax.swing.JButton();
        paneVotos = new javax.swing.JScrollPane();
        tabelaVotos = new javax.swing.JTable();
        jVotar = new javax.swing.JButton();
        jtextoVoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        paneUsers.setViewportView(tabelaUsers);

        jMessagePane.setEditable(false);
        paneConversa.setViewportView(jMessagePane);

        jSairSala.setText("Sair");
        jSairSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairSalaActionPerformed(evt);
            }
        });

        buttonEnviar.setText("Enviar");
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });

        paneVotos.setAutoscrolls(true);

        tabelaVotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        paneVotos.setViewportView(tabelaVotos);

        jVotar.setText("Votar");
        jVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVotarActionPerformed(evt);
            }
        });

        jtextoVoto.setText("Você ainda não votou");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneConversa, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonEnviar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jVotar)
                                .addGap(18, 18, 18)
                                .addComponent(jtextoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(paneVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(paneUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSairSala)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSairSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneConversa, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEnviar))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jVotar)
                            .addComponent(jtextoVoto))
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSairSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairSalaActionPerformed
        cliente.sairSala();
    }//GEN-LAST:event_jSairSalaActionPerformed

    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        cliente.enviarMsg(jMensagem.getText());
        jMensagem.setText("");
    }//GEN-LAST:event_buttonEnviarActionPerformed

    private void jVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVotarActionPerformed
        int pos = tabelaVotos.getSelectedRow();
        String s = tabelaVotos.getValueAt(pos, 0).toString();
        if(s != null) cliente.votar(s);
        System.out.println(s);
    }//GEN-LAST:event_jVotarActionPerformed

public void atualizarVoto(String info){
    if(info.equals("")) jtextoVoto.setText("Você ainda não votou");
    else jtextoVoto.setText("Você votou em: " + info);
}
    
public void atualizarListaUsers(DefaultTableModel model){
    modeloTabelaUsuarios = model;
    tabelaUsers.setModel(modeloTabelaUsuarios);
}

public void atualizarListaVotos(DefaultTableModel model){
    modeloTabelaVotos = model;
    tabelaVotos.setModel(modeloTabelaVotos);
}

public void atualizarMensagens(String mensagem, String criador, Date time){
    String stringdata = df.format(time);
    String printThis = "(" + stringdata + ") " + criador + ":\n" + "                    " + mensagem + "\n";
    try {
         doc.insertString(doc.getLength(), printThis + "\n", style);
    } catch (BadLocationException ex) {
        Logger.getLogger(ViewDiscussao.class.getName()).log(Level.SEVERE, null, ex);
    }
    jMessagePane.setStyledDocument(doc);
}

public void limparMensagens(){
    doc = new DefaultStyledDocument();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JTextField jMensagem;
    private javax.swing.JTextPane jMessagePane;
    private javax.swing.JButton jSairSala;
    private javax.swing.JButton jVotar;
    private javax.swing.JLabel jtextoVoto;
    private javax.swing.JScrollPane paneConversa;
    private javax.swing.JScrollPane paneUsers;
    private javax.swing.JScrollPane paneVotos;
    private javax.swing.JTable tabelaUsers;
    private javax.swing.JTable tabelaVotos;
    // End of variables declaration//GEN-END:variables
}
