/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModelCliente;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author tofet
 */
public class ViewDiscussao extends javax.swing.JFrame {

    private DefaultTableModel modeloTabelaUsuarios;
    private ModelCliente cliente;
    private StyledDocument doc;
    
    public ViewDiscussao() {
        initComponents();
        doc = new DefaultStyledDocument();
        StyleContext context = new StyleContext();
        Style style = context.addStyle("test", null);
        StyleConstants.setForeground(style, Color.BLACK);
        try {
            doc.insertString(0, "TEstansadoasoda", style);
        } catch (BadLocationException ex) {
            Logger.getLogger(ViewDiscussao.class.getName()).log(Level.SEVERE, null, ex);
        }
        jMessagePane.setStyledDocument(doc);
        jMessagePane.setEditable(false);
    }
    
    public void setCliente(ModelCliente client){
        cliente = client;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneUsers = new javax.swing.JScrollPane();
        tabelaUsers = new javax.swing.JTable();
        paneConversa = new javax.swing.JScrollPane();
        jMessagePane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        paneUsers.setViewportView(tabelaUsers);

        jMessagePane.setEditable(false);
        paneConversa.setViewportView(jMessagePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(paneConversa, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(paneUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneConversa, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void atualizarListaUsers(DefaultTableModel model){
    modeloTabelaUsuarios = model;
    tabelaUsers.setModel(modeloTabelaUsuarios);
}

public void atualizarMensagens(StyledDocument doc){
    jMessagePane.setStyledDocument(doc);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane jMessagePane;
    private javax.swing.JScrollPane paneConversa;
    private javax.swing.JScrollPane paneUsers;
    private javax.swing.JTable tabelaUsers;
    // End of variables declaration//GEN-END:variables
}
