/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModelCliente;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.json.*;
/**
 *
 * @author gabriel
 */
public class ViewLogin extends JFrame {

    private DefaultTableModel modeloTabelaSalas;
    private DefaultTableModel modeloTabelaUsuarios;
    private ModelCliente cliente;
    private int serverPort;
    private InetAddress host;
    private DatagramSocket socketCliente;
    private ViewPrincipal viewprincipal;
    private ViewDiscussao viewdiscussao;

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() throws InterruptedException, UnknownHostException {
        beginStuff();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        LabelLogin = new javax.swing.JLabel();
        TextFieldLogin = new javax.swing.JTextField();
        LabelSenha = new javax.swing.JLabel();
        TextFieldSenha = new javax.swing.JTextField();
        ButtonLoginOK = new javax.swing.JButton();
        ButtonLoginLimpar = new javax.swing.JButton();
        TextFieldPort = new javax.swing.JTextField();
        TextFieldIP = new javax.swing.JTextField();
        LabelPort = new javax.swing.JLabel();
        LabelServer = new javax.swing.JLabel();
        LabelTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelLogin.setText("LOGIN:");

        LabelSenha.setText("SENHA:");

        ButtonLoginOK.setText("OK");
        ButtonLoginOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginOKActionPerformed(evt);
            }
        });

        ButtonLoginLimpar.setText("Limpar");
        ButtonLoginLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginLimparActionPerformed(evt);
            }
        });

        TextFieldPort.setText("20000");

        TextFieldIP.setText("localhost");

        LabelPort.setText("PORT:");

        LabelServer.setText("SERVER:");

        LabelTela.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelTela.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(ButtonLoginOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonLoginLimpar)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelLogin)
                                    .addComponent(LabelPort))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelServer)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldIP)
                            .addComponent(TextFieldPort)
                            .addComponent(TextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTela)
                .addGap(142, 142, 142))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonLoginLimpar, ButtonLoginOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelServer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPort))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLogin)
                    .addComponent(TextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSenha))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLoginOK)
                    .addComponent(ButtonLoginLimpar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLoginOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginOKActionPerformed
        try {
            cliente.setHost(InetAddress.getByName(TextFieldIP.getText()));
        } catch (UnknownHostException ex) {
            Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        cliente.setPorta(Integer.parseInt(TextFieldPort.getText()));//seta dentro do cliente essas variaveis
        cliente.setSenha(TextFieldSenha.getText());
        cliente.setLogin(TextFieldLogin.getText());
        cliente.fazerLogin();
        
        this.setVisible(false);
        viewprincipal.setVisible(true);
    }//GEN-LAST:event_ButtonLoginOKActionPerformed

    private void ButtonLoginLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginLimparActionPerformed
        TextFieldIP.setText("");
        TextFieldLogin.setText("");
        TextFieldPort.setText("");
        TextFieldSenha.setText("");
    }//GEN-LAST:event_ButtonLoginLimparActionPerformed

    private void beginStuff() throws UnknownHostException, InterruptedException{ 
        //instancia as outras interfaces e o controle do cliente, e faz com que todo mundo saiba sobre todo mundo
        viewprincipal = new ViewPrincipal();
        viewdiscussao = new ViewDiscussao();
        
        cliente = new ModelCliente(viewprincipal, viewdiscussao);
        cliente.init();
        viewprincipal.setCliente(cliente);
        viewdiscussao.setCliente(cliente);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLoginLimpar;
    private javax.swing.JButton ButtonLoginOK;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelPort;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelServer;
    private javax.swing.JLabel LabelTela;
    private javax.swing.JTextField TextFieldIP;
    private javax.swing.JTextField TextFieldLogin;
    private javax.swing.JTextField TextFieldPort;
    private javax.swing.JTextField TextFieldSenha;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
